apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clh-apps-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: bgd-qa
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: bdg/overlays/qa
      repoURL: https://github.com/mcaballol/poc-gitops-github.git
      targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true